---
- name: Instalacion de Servidor Apache
  hosts: localhost
  connection: local
  

  tasks:
    - name: crear maquina target-redhat-01
      community.docker.docker_container:
        name: target-redhat-01
        image: lscr.io/linuxserver/openssh-server:latest
        state: started
        restart_policy: unless-stopped
        env:
          USER_NAME: "ansible"
          USER_PASSWORD: "ansible123"
          PASSWORD_ACCESS: "true"
          SUDO_ACCESS: "true"
        ports:
          - "2223:22"
          - "8082:80"
    