---
- name: Instalacion de Servidor Apache
  hosts: localhost
  connection: local
  

  tasks:
    - name: crear maquina target-redhat-01
      community.docker.docker_container:
        name: target-redhat-01
        image: lscr.io/linuxserver/openssh-server:latest
        state: started
        restart_policy: unless-stopped
        env:
          SSH_ENABLE_PASSWORD_AUTH: "true"
          ansible: "ansible123"
          SUDO_USERS: "ansible"
          ansibleALL: "(ALL)NOPASSWD:ALL"
        ports:
          - "2223:22"
          - "8082:80"
    