---
- name: Instalación de servidor httpd
  hosts: target-redhat-01
  become: yes

  tasks:
    - name: instalacion de paquete httpd
      ansible.builtin.dnf:
        name: httpd
        state: lastet

    - name: subir el servicio
      ansible.builtin.service:
        name: httpd
        state: start
        enable: yes

    - name: crear html
      ansible.builtin.copy:
        conte: "<h1>el servidor apache esta activo</h1>"
        dest: /var/www/html/inde.html
