---
- name: Instalación de servidor httpd
  hosts: target-redhat-01
  become: yes

  tasks:
    - name: instalacion de paquete httpd
      ansible.builtin.package:
        name: apache2
        state: present

    - name: subir el servicio
      ansible.builtin.file:
        path: /var/www/localhost/htdocs
        state: directory
        mode: "0755"

    - name: crear html
      ansible.builtin.copy:
        content: "<h1>el servidor apache esta activo</h1>"
        dest: /var/www/html/index.html
